# Config file for Air live-reloading tool in Go

root = "."
test_data_dir = "testdata"
tmp_dir = "tmp"

[build]
  # We specify the correct entrypoint to compile our cmd/print-agent-gui package
  cmd = "go build -o ./tmp/main ./cmd/print-agent-gui/main.go"
  bin = "./tmp/main"
  
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "web"]
  exclude_file = []
  exclude_regex = ["_test\\.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["cmd", "internal"]
  include_ext = ["go", "html", "toml"]
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
