package escpos

import (
	"strings"
	"testing"
)

func TestFormatRupiah(t *testing.T) {
	tests := []struct {
		input    int
		expected string
	}{
		{0, "Rp 0"},
		{500, "Rp 500"},
		{1000, "Rp 1.000"},
		{15000, "Rp 15.000"},
		{250000, "Rp 250.000"},
		{1000000, "Rp 1.000.000"},
		{-5000, "-Rp 5.000"},
	}

	for _, tc := range tests {
		actual := FormatRupiah(tc.input)
		if actual != tc.expected {
			t.Errorf("FormatRupiah(%d) = %q, expected %q", tc.input, actual, tc.expected)
		}
	}
}

func TestWrapText(t *testing.T) {
	tests := []struct {
		text     string
		width    int
		expected []string
	}{
		{"Short text", 32, []string{"Short text"}},
		{"", 32, []string{""}},
		{
			"Super Premium Delicious Roasted Coffee Beans Medium Blend",
			32,
			[]string{
				"Super Premium Delicious Roasted",
				"Coffee Beans Medium Blend",
			},
		},
		{
			"Supercalifragilisticexpialidocious", // 34 chars
			10,
			[]string{
				"Supercalif",
				"ragilistic",
				"expialidoc",
				"ious",
			},
		},
	}

	for _, tc := range tests {
		actual := WrapText(tc.text, tc.width)
		if len(actual) != len(tc.expected) {
			t.Fatalf("WrapText(%q, %d) returned %d lines, expected %d. Got: %v", tc.text, tc.width, len(actual), len(tc.expected), actual)
		}
		for i := range actual {
			if actual[i] != tc.expected[i] {
				t.Errorf("WrapText(%q, %d) line %d = %q, expected %q", tc.text, tc.width, i, actual[i], tc.expected[i])
			}
		}
	}
}

func TestFormatLine(t *testing.T) {
	tests := []struct {
		left     string
		right    string
		width    int
		expected string
	}{
		{"Subtotal", "Rp 25.000", 32, "Subtotal               Rp 25.000"},
		{"GRAND TOTAL", "Rp 125.000", 32, "GRAND TOTAL           Rp 125.000"},
		{"ExtremelyLongLeftPartHere", "ShortRight", 10, "ExtremelyLongLeftPartHere ShortRight"},
	}

	for _, tc := range tests {
		actual := FormatLine(tc.left, tc.right, tc.width)
		if actual != tc.expected {
			t.Errorf("FormatLine(%q, %q, %d) = %q (len %d), expected %q (len %d)", tc.left, tc.right, tc.width, actual, len(actual), tc.expected, len(tc.expected))
		}
	}
}

func TestGenerateESCPOSText(t *testing.T) {
	r := Receipt{
		StoreName: "TEST STORE",
		Cashier:   "Test Cashier",
		InvoiceNo: "INV-TEST",
		Items: []Item{
			{Name: "Item A", Qty: 1, Price: 10000, Total: 10000},
			{Name: "Item B", Qty: 2, Price: 7500, Total: 15000},
		},
		Subtotal:      25000,
		Discount:      0,
		Tax:           0,
		GrandTotal:    25000,
		PaymentMethod: "Cash",
		Paid:          30000,
		Change:        5000,
		Footer:        "Thank you for testing",
		KickDrawer:    true,
	}

	bytes, err := GenerateESCPOSText(r)
	if err != nil {
		t.Fatalf("GenerateESCPOSText returned unexpected error: %v", err)
	}

	if len(bytes) == 0 {
		t.Fatal("GenerateESCPOSText returned empty byte slice")
	}

	// Verify that it contains store name, invoice, cash drawer kick, and footer
	strBytes := string(bytes)
	if !strings.Contains(strBytes, "TEST STORE") {
		t.Error("Generated bytes missing store name")
	}
	if !strings.Contains(strBytes, "INV-TEST") {
		t.Error("Generated bytes missing invoice number")
	}
	if !strings.Contains(strBytes, "Thank you for testing") {
		t.Error("Generated bytes missing footer")
	}

	// Verify default 32-character divider
	if !strings.Contains(strBytes, strings.Repeat("-", 32)) {
		t.Error("Generated bytes missing default 32-character divider")
	}

	// Verify dynamic 48-character (80mm) custom width
	r.Width = 48
	bytes48, err := GenerateESCPOSText(r)
	if err != nil {
		t.Fatalf("GenerateESCPOSText with width 48 failed: %v", err)
	}
	strBytes48 := string(bytes48)
	if !strings.Contains(strBytes48, strings.Repeat("-", 48)) {
		t.Error("Generated bytes missing custom 48-character divider")
	}
}

func TestGenerateTaskTicket(t *testing.T) {
	task := TaskTicket{
		TaskID:      "TSK-9999",
		Title:       "Espresso Backflush Clean",
		Description: "Run Cafiza cleaning powder cycle for 10 repetitions.",
		Priority:    "High",
		Assignee:    "John Doe",
		DueDate:     "30-05-2026",
	}

	bytes, err := GenerateTaskTicket(task)
	if err != nil {
		t.Fatalf("GenerateTaskTicket returned unexpected error: %v", err)
	}

	if len(bytes) == 0 {
		t.Fatal("GenerateTaskTicket returned empty byte slice")
	}

	strBytes := string(bytes)
	if !strings.Contains(strBytes, "TASK TICKET") {
		t.Error("Generated bytes missing TASK TICKET header")
	}
	if !strings.Contains(strBytes, "TSK-9999") {
		t.Error("Generated bytes missing ticket task ID")
	}
	if !strings.Contains(strBytes, "*** HIGH ***") {
		t.Error("Generated bytes missing HIGH priority bold indicator")
	}
	if !strings.Contains(strBytes, "John Doe") {
		t.Error("Generated bytes missing assignee name")
	}
	if !strings.Contains(strBytes, "Espresso Backflush Clean") {
		t.Error("Generated bytes missing task title")
	}
}

func TestGenerateGenericReceipt(t *testing.T) {
	gr := GenericReceipt{
		Width: 32,
		Lines: []GenericLine{
			{Type: "text", Text: "GENERIC STORE", Align: "CENTER", Bold: true, Size: "DOUBLE_HW"},
			{Type: "divider", Char: "-"},
			{Type: "columns", Left: "Item 1", Right: "Rp 15.000"},
			{Type: "columns", Left: "Item 2", Right: "Rp 25.000"},
			{Type: "divider", Char: "="},
			{Type: "columns", Left: "TOTAL", Right: "Rp 40.000", Bold: true},
			{Type: "cut"},
		},
	}

	bytes, err := GenerateGenericReceipt(gr)
	if err != nil {
		t.Fatalf("GenerateGenericReceipt returned unexpected error: %v", err)
	}

	if len(bytes) == 0 {
		t.Fatal("GenerateGenericReceipt returned empty byte slice")
	}

	strBytes := string(bytes)
	if !strings.Contains(strBytes, "GENERIC STORE") {
		t.Error("Generated bytes missing generic header")
	}
	if !strings.Contains(strBytes, "Item 1") {
		t.Error("Generated bytes missing generic Item 1")
	}
	if !strings.Contains(strBytes, "TOTAL") {
		t.Error("Generated bytes missing generic TOTAL")
	}
	if !strings.Contains(strBytes, strings.Repeat("=", 32)) {
		t.Error("Generated bytes missing generic double divider")
	}
}

